name = "pickglass"
version = "0.1.0"
licences = ["Apache-2.0"]
description = "A BEAM runtime inspector and performance and trace viewer, written in Gleam."
target = "erlang"

gleam = ">= 1.19.0-rc2"

repository = { type = "github", user = "Roasbeef", repo = "pickglass" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.3.0 and < 2.0.0"
weft = ">= 0.4.5 and < 1.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
argv = ">= 1.0.0 and < 2.0.0"
pickglass_core = { path = "../core" }
pickglass_web = { path = "../web" }
mist = ">= 6.0.3 and < 7.0.0"
lustre = "== 5.7.1"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
gleam_http = ">= 4.4.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
exception = ">= 2.1.1 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 1.0.5 and < 2.0.0"
