#!/usr/bin/env escript
%%% Beam import check for the pushed agent.
%%%
%%% The agent is loaded into a node it does not own. Any module it calls that
%%% is not part of the agent or of the OTP the node already runs would either
%%% be missing there or, if the agent shipped a copy, replace the target's
%%% own. This script reads the import table of every compiled agent beam and
%%% fails when a call leaves the agent's own `pickglass_agent@` modules and
%%% the allowed OTP modules below.
%%%
%%% Usage: escript scripts/agent_imports.escript <ebin directory>
%%%
%%% `pickglass_agent@@main.beam` is generated by the Gleam compiler for
%%% `gleam run` and imports the standard library. It is never pushed, so it
%%% is skipped here, and the viewer skips it too. Only `pickglass_agent@*`
%%% files are checked, because that is the set the viewer pushes: the build
%%% directory also holds test modules after `gleam test`.
-mode(compile).

%% The modules plan.md allows, plus `gen_server` (the receive loop: Gleam has
%% no `receive`, and a hand-written Erlang module is the alternative) and
%% `rpc` (the only construct that turns a raised exception into a value
%% without a dependency). Both are kernel/stdlib modules every node has.
allowed() ->
    [erlang, trace, instrument, ets, code, erts_debug, proc_lib,
     lists, maps, os, gen_server, rpc].

main([Dir]) ->
    Beams = [F || F <- filelib:wildcard(filename:join(Dir, "pickglass_agent@*.beam")),
                  not is_main(F)],
    case Beams of
        [] -> fail("no agent beams found in ~s", [Dir]);
        _ -> ok
    end,
    Bad = lists:flatmap(fun check/1, Beams),
    case Bad of
        [] ->
            io:format("agent imports: ~b modules, every call stays in "
                      "pickglass_agent@* or the allowed OTP modules~n",
                      [length(Beams)]);
        _ ->
            [io:format("agent imports: ~s calls ~s:~s/~b~n",
                       [Mod, M, F, A]) || {Mod, {M, F, A}} <- Bad],
            halt(1)
    end;
main(_) ->
    fail("usage: agent_imports.escript <ebin directory>", []).

is_main(File) ->
    filename:basename(File) =:= "pickglass_agent@@main.beam".

check(File) ->
    {ok, {Module, [{imports, Imports}]}} = beam_lib:chunks(File, [imports]),
    Name = atom_to_list(Module),
    case lists:prefix("pickglass_agent@", Name) of
        false -> [{Name, {Module, module, 0}}];
        true -> [{Name, I} || {M, _, _} = I <- Imports, not permitted(M)]
    end.

permitted(M) ->
    lists:member(M, allowed()) orelse
        lists:prefix("pickglass_agent@", atom_to_list(M)).

fail(Fmt, Args) ->
    io:format("agent imports: " ++ Fmt ++ "~n", Args),
    halt(1).
