#!/usr/bin/env bash
# Build a self-contained OTP release of Pickglass into build/release/pickglass,
# the BEAM runtime system included, so the machine that runs `pickglass`
# needs no Erlang installed.
#
#   scripts/release.sh          # build the release tree
#   scripts/release.sh --smoke  # boot it with no erl on PATH
#
# The mechanism is Loom's (scripts/release-client.sh). A plain erlang
# shipment is compiled BEAM files that need an OTP installation on the host;
# `gleam export erlang-shipment` produces one, rebar3's relx assembles the
# applications in it into an OTP release, and `include_erts` copies the
# runtime system in beside them. relx works out the OTP application closure
# from `lib_dirs` by itself. The copied ERTS is this machine's, so a release
# is per-platform by construction.
#
# `runtime_tools` is in the release closure on purpose: a runtime inspector
# is the program most likely to want the VM's own tracing and
# introspection applications at run time.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

PKG=packages/pickglass
REL_ROOT="$ROOT/build/release"
REL="$REL_ROOT/pickglass"
WORK="$REL_ROOT/work"
STRIP_ERTS="${DIST_STRIP_ERTS:-1}"
SMOKE=0
[ "${1-}" = "--smoke" ] && SMOKE=1

# The version is read from gleam.toml, the one place that declares it, so
# the release name, the launcher and the smoke comparison cannot disagree.
VERSION="$(sed -n 's/^version *= *"\(.*\)"/\1/p' "$PKG/gleam.toml" | head -1)"
[ -n "$VERSION" ] || { echo "release.sh: no version in $PKG/gleam.toml" >&2; exit 1; }

# ------------------------------------------------------------ smoke only
# The claim under test is that the built release runs with no Erlang on the
# host, so the smoke asks nothing of PATH beyond the system shell tools. It
# first proves the claim is a real test (no `erl` is reachable on that PATH),
# then runs the launcher and compares what it printed with the version in
# gleam.toml.
if [ "$SMOKE" = 1 ]; then
  [ -x "$REL/bin/pickglass" ] || {
    echo "release.sh: no release at $REL — run \`make release\` first" >&2
    exit 1; }
  SMOKE_PATH=/usr/bin:/bin
  if PATH="$SMOKE_PATH" command -v erl >/dev/null 2>&1; then
    echo "release smoke: erl is on the minimal PATH, so the test proves nothing" >&2
    exit 1
  fi
  out="$(env -i PATH="$SMOKE_PATH" HOME="${HOME:-/tmp}" "$REL/bin/pickglass" 2>&1 || true)"
  expected="pickglass $VERSION"
  if [ "$out" != "$expected" ]; then
    echo "release smoke: the launcher printed the wrong thing" >&2
    printf '  expected: %s\n  got:      %s\n' "$expected" "$out" >&2
    exit 1
  fi
  echo "release smoke: the bundled runtime printed \"$out\" with no erl on PATH"
  exit 0
fi

# ------------------------------------------------------------ preflight
missing=""
need() { command -v "$1" >/dev/null 2>&1 || missing="$missing  $1 — $2\n"; }
need gleam  "exports the package as an erlang shipment (>= 1.19.0)"
need rebar3 "assembles the OTP release and copies ERTS into it"
need erl    "the runtime system that gets copied in (OTP >= 29)"
if [ "$STRIP_ERTS" = 1 ]; then
  need strip "strips the copied ERTS binaries (DIST_STRIP_ERTS=0 to skip)"
fi
if [ -n "$missing" ]; then
  printf 'release.sh: cannot build a release, these are not on PATH:\n' >&2
  printf '%b' "$missing" >&2
  exit 1
fi
ERTS_VSN="$(erl -noshell -eval 'io:format("~s",[erlang:system_info(version)]),halt().')"

# ------------------------------------------------------------ the build
echo "==> exporting the shipment"
( cd "$PKG" && gleam export erlang-shipment >/dev/null )
rm -rf "$REL" "$WORK"
mkdir -p "$WORK/libs"
cp -R "$PKG/build/erlang-shipment/." "$WORK/libs/"
rm -f "$WORK/libs/entrypoint.sh" "$WORK/libs/entrypoint.ps1"

# The agent is not part of the release's own code: the viewer pushes it into
# the target at run time. It ships as data in the viewer's priv directory,
# where `agent_beams` looks first. Only the `pickglass_agent@` modules go, and
# not the compiler's `@@main` entry module, which imports the standard
# library and must never be loaded into a target.
echo "==> building the agent"
( cd packages/agent && gleam build >/dev/null )
mkdir -p "$WORK/libs/pickglass/priv/agent"
for beam in packages/agent/build/dev/erlang/pickglass_agent/ebin/pickglass_agent@*.beam; do
  case "$beam" in *@@main.beam) continue ;; esac
  cp "$beam" "$WORK/libs/pickglass/priv/agent/"
done

cat > "$WORK/rebar.config" <<CONFIG
%% Generated by scripts/release.sh. Edit the script, not this file.
{erl_opts, []}.
{deps, []}.
{project_app_dirs, []}.
{relx, [
  {release, {pickglass, "$VERSION"}, [pickglass, runtime_tools]},
  {lib_dirs, ["libs"]},
  {include_erts, true},
  {include_src, false},
  {dev_mode, false},
  {debug_info, strip}
]}.
CONFIG

echo "==> assembling the release (rebar3 relx)"
( cd "$WORK" && rebar3 release )
mkdir -p "$REL_ROOT"
mv "$WORK/_build/default/rel/pickglass" "$REL"
rm -rf "$WORK"

# relx's own launcher is a distributed-node supervisor with a guessable
# cookie, and a runtime inspector has no business shipping that default.
# vm.args and sys.config are read only by that launcher. The *.boot files
# stay because the bundled emulator boots from bin/.
find "$REL/bin" -maxdepth 1 -type f ! -name '*.boot' -delete
rm -f "$REL/releases/$VERSION/vm.args" \
      "$REL/releases/$VERSION/sys.config"
[ -f "$REL/bin/no_dot_erlang.boot" ] || {
  echo "release.sh: relx left no bin/no_dot_erlang.boot" >&2; exit 1; }

if [ "$STRIP_ERTS" = 1 ]; then
  echo "==> stripping the copied ERTS"
  find "$REL/erts-$ERTS_VSN/bin" -type f -exec sh -c '
    file -b "$1" | grep -q "ELF.*not stripped" && strip -s "$1"' _ {} \; || true
fi

# The launcher is the shipment entrypoint's invocation over the bundled
# `erl`, booting `no_dot_erlang` so nobody's ~/.erlang runs inside the
# program. Arguments are passed through after `-extra`.
#
# `-nocookie` gives the viewer's VM no distribution cookie of its own. Without
# it, starting distribution makes OTP's `auth` create ~/.erlang.cookie in the
# operator's home. The viewer does not listen, so nothing connects to it, and
# the only cookie it uses is the target's, set per peer after it is read from
# the target's owner-only file.
cat > "$REL/bin/pickglass" <<LAUNCHER
#!/usr/bin/env bash
# Generated by scripts/release.sh. The Pickglass launcher.
set -euo pipefail
here=\$(CDPATH= cd -- "\$(dirname -- "\$0")" && pwd -P)
root=\$(dirname "\$here")
exec "\$root/erts-$ERTS_VSN/bin/erl" +Bd \\
  -nocookie \\
  -boot "\$root/bin/no_dot_erlang" \\
  -pa "\$root"/lib/*/ebin \\
  -noshell \\
  -eval 'pickglass@@main:run(pickglass)' \\
  -extra "\$@"
LAUNCHER
chmod +x "$REL/bin/pickglass"

SHA256=sha256sum
command -v sha256sum >/dev/null 2>&1 || SHA256="shasum -a 256"
( cd "$REL" && find . -type f -perm -u+x | LC_ALL=C sort -u \
    | tr '\n' '\0' | xargs -0 $SHA256 > SHA256SUMS )

echo
echo "release: $REL"
for p in "$REL" "$REL/erts-$ERTS_VSN" "$REL/lib"; do
  du -sh "$p" | sed 's/^/  /'
done
